In [1]:
import pandas as pd
df = pd.read_csv("S04_PD_Gonzalez_DatasetImputacionInicial.csv")

## Etapa 1: Limpieza de inconsistencias y duplicados

In [2]:
for col in ["ciudad_tienda", "categoria_producto", "canal_compra", "metodo_pago"]: print(col, sorted(df[col].dropna().unique()))

ciudad_tienda [' Barranquilla', ' Bogotá', ' Bucaramanga', ' Cali', ' Cartagena', ' Cúcuta', ' Ibagué', ' Manizales', ' Medellín', ' Pereira', ' Santa Marta', ' Villavicencio', 'B/manga', 'B/quilla', 'BAQ', 'BARRANQUILLA', 'BGA', 'BOG', 'BOGOTA', 'BOGOTA DC', 'BOGOTÁ', 'BUCARAMANGA', 'Barranquilla', 'Barranquilla ', 'Bogota', 'Bogota D.C.', 'Bogotá', 'Bogotá ', 'Bucaramanga', 'Bucaramanga ', 'CALI', 'CALI ', 'CARTAGENA', 'CTG', 'CUCUTA', 'Cali', 'Cali ', 'Cartagena', 'Cartagena ', 'Cartagena de Indias', 'Cucuta', 'CÚCUTA', 'Cúcuta', 'Cúcuta ', 'IBAGUE', 'IBAGUÉ', 'Ibague', 'Ibagué', 'Ibagué ', 'MANIZALES', 'MDE', 'MEDELLIN', 'MEDELLÍN', 'MZL', 'Manizales', 'Manizales ', 'Manizales, Caldas', 'Medellin', 'Medellin, Ant.', 'Medellín', 'Medellín ', 'PEREIRA', 'Pereira', 'Pereira ', 'SANTA MARTA', 'SMR', 'Santa Marta', 'Santa Marta ', 'SantaMarta', 'Santiago de Cali', 'Sta. Marta', 'VILLAVICENCIO', 'Villavicencio', 'Villavicencio ', 'barranquilla', 'bogota', 'bogota d.c.', 'bucaramanga', 'cali', 'cartagena', 'cucuta', 'ibague', 'manizales', 'medellin', 'pereira', 'santa marta', 'santamarta', 'villavicencio']
categoria_producto [' Belleza', ' Deportes', ' Electrónica', ' Hogar', ' Juguetería', ' Moda', 'BELLEZA', 'Belleza', 'Belleza ', 'DEPORTES', 'Deportes', 'Deportes ', 'ELECTRÓNICA', 'Electrónica', 'Electrónica ', 'HOGAR', 'Hogar', 'Hogar ', 'JUGUETERÍA', 'Juguetería', 'Juguetería ', 'MODA', 'Moda', 'Moda ', 'belleza', 'deportes', 'electronica', 'electrónica', 'hogar', 'jugueteria', 'juguetería', 'moda']
canal_compra [' App', ' Marketplace', ' Tienda', ' Web', 'APP', 'App', 'App ', 'MARKETPLACE', 'Marketplace', 'Marketplace ', 'TIENDA', 'Tienda', 'Tienda ', 'WEB', 'Web', 'Web ', 'app', 'marketplace', 'tienda', 'web']
metodo_pago [' Efectivo', ' PayPal', ' Tarjeta', ' Transferencia', 'EFECTIVO', 'Efectivo', 'Efectivo ', 'PAYPAL', 'PayPal', 'PayPal ', 'TARJETA', 'TRANSFERENCIA', 'Tarjeta', 'Tarjeta ', 'Transferencia', 'Transferencia ', 'efectivo', 'paypal', 'tarjeta', 'transferencia']

In [3]:
df["ciudad_tienda"] = df["ciudad_tienda"].str.strip().str.title()

df["categoria_producto"] = df["categoria_producto"].str.strip().str.title()

df["canal_compra"] = df["canal_compra"].str.strip().str.title()

df["metodo_pago"] = df["metodo_pago"].str.strip().str.title()

In [4]:
for col in ["ciudad_tienda", "categoria_producto", "canal_compra", "metodo_pago"]: print(col, sorted(df[col].dropna().unique()))

ciudad_tienda ['B/Manga', 'B/Quilla', 'Baq', 'Barranquilla', 'Bga', 'Bog', 'Bogota', 'Bogota D.C.', 'Bogota Dc', 'Bogotá', 'Bucaramanga', 'Cali', 'Cartagena', 'Cartagena De Indias', 'Ctg', 'Cucuta', 'Cúcuta', 'Ibague', 'Ibagué', 'Manizales', 'Manizales, Caldas', 'Mde', 'Medellin', 'Medellin, Ant.', 'Medellín', 'Mzl', 'Pereira', 'Santa Marta', 'Santamarta', 'Santiago De Cali', 'Smr', 'Sta. Marta', 'Villavicencio']
categoria_producto ['Belleza', 'Deportes', 'Electronica', 'Electrónica', 'Hogar', 'Jugueteria', 'Juguetería', 'Moda']
canal_compra ['App', 'Marketplace', 'Tienda', 'Web']
metodo_pago ['Efectivo', 'Paypal', 'Tarjeta', 'Transferencia']

In [5]:
correcciones_ciudad = {
    # Barranquilla
    "B/Quilla": "Barranquilla",
    "Baq": "Barranquilla",

    # Bogotá
    "Bog": "Bogotá",
    "Bogota": "Bogotá",
    "Bogota D.C.": "Bogotá",
    "Bogota Dc": "Bogotá",

    # Bucaramanga
    "B/Manga": "Bucaramanga",
    "Bga": "Bucaramanga",

    # Cali
    "Santiago De Cali": "Cali",

    # Cartagena
    "Cartagena De Indias": "Cartagena",
    "Ctg": "Cartagena",

    # Cúcuta
    "Cucuta": "Cúcuta",

    # Ibagué
    "Ibague": "Ibagué",

    # Manizales
    "Manizales, Caldas": "Manizales",
    "Mzl": "Manizales",

    # Medellín
    "Mde": "Medellín",
    "Medellin": "Medellín",
    "Medellin, Ant.": "Medellín",

    # Santa Marta
    "Santamarta": "Santa Marta",
    "Smr": "Santa Marta",
    "Sta. Marta": "Santa Marta"
}

correcciones_categoria = {
    "Electronica": "Electrónica",
    "Jugueteria": "Juguetería"
}

df["ciudad_tienda"] = df["ciudad_tienda"].replace(correcciones_ciudad)
df["categoria_producto"] = df["categoria_producto"].replace(correcciones_categoria)

In [6]:
df["ciudad_tienda"].unique()

array(['Bogotá', 'Manizales', 'Cúcuta', 'Bucaramanga', 'Medellín',
       'Pereira', 'Cali', 'Santa Marta', 'Ibagué', 'Villavicencio',
       'Cartagena', 'Barranquilla'], dtype=object)

In [7]:
df["categoria_producto"].unique()

array(['Moda', 'Electrónica', 'Juguetería', 'Deportes', 'Hogar',
       'Belleza'], dtype=object)

In [8]:
df["canal_compra"].unique()

array(['Tienda', 'Web', 'App', 'Marketplace'], dtype=object)

In [9]:
df["metodo_pago"].unique()

array(['Efectivo', 'Paypal', 'Transferencia', 'Tarjeta'], dtype=object)

In [10]:
meses_map = {
    "-ene-": "-01-", "/ene/": "/01/",
    "-feb-": "-02-", "/feb/": "/02/",
    "-mar-": "-03-", "/mar/": "/03/",
    "-abr-": "-04-", "/abr/": "/04/",
    "-may-": "-05-", "/may/": "/05/",
    "-jun-": "-06-", "/jun/": "/06/",
    "-jul-": "-07-", "/jul/": "/07/",
    "-ago-": "-08-", "/ago/": "/08/",
    "-sep-": "-09-", "/sep/": "/09/",
    "-oct-": "-10-", "/oct/": "/10/",
    "-nov-": "-11-", "/nov/": "/11/",
    "-dic-": "-12-", "/dic/": "/12/"
}

fecha_str = df["fecha_pedido"].astype(str)

for k, v in meses_map.items():
    fecha_str = fecha_str.str.replace(k, v, case=False, regex=False)

df["fecha_pedido"] = pd.to_datetime(fecha_str, format="mixed", errors="coerce")

print("Nulos en fecha_pedido:", df["fecha_pedido"].isnull().sum())

Nulos en fecha_pedido: 20922

In [11]:
df.duplicated(subset=["correo_cliente"], keep=False).sum()

np.int64(127682)

In [12]:
df[df.duplicated(subset=["correo_cliente"], keep=False)].sort_values("correo_cliente")

,id_pedido,id_cliente,fecha_pedido,canal_compra,metodo_pago,ciudad_tienda,codigo_postal,categoria_producto,producto,precio_unitario,...,monto_compra,edad_cliente,correo_cliente,nivel_satisfaccion,nivel_lealtad,comentario_cliente,peso_pedido_kg,fecha_actualizacion_stock,fuga_cliente,nivel_satisfaccion_imputado
275899,P200040,C51427,2025-07-16,Tienda,Tarjeta,Cali,7600111,Belleza,Kit de brochas,155300.0,...,621200.0,-5,cliente100040@hotmail.com,Bajo,Oro,NaN,10.4,2027-11-06,1,False
259291,P200040,C51427,2025-07-16,Tienda,Tarjeta,Cali,7600111,Belleza,Kit de brochas,155300.0,...,621200.0,-5,cliente100040@hotmail.com,Bajo,Oro,NaN,10.4,2027-11-06,1,False
499677,P200097,C53819,2025-05-11,Web,Paypal,Bogotá,1100125,Moda,Camisa de lino,786900.0,...,1573800.0,35,cliente100097@hotmail.com,Bajo,Bronce,"Excelente calidad, volvería a comprar",10.6,2026-05-11,0,False
439514,P200097,C53819,2025-05-11,Web,Paypal,Bogotá,1100125,Moda,Camisa de lino,786900.0,...,1573800.0,35,cliente100097@hotmail.com,Bajo,Bronce,"Excelente calidad, volvería a comprar",10.6,2026-05-11,0,False
513581,P200116,C152336,NaT,Web,Paypal,Manizales,1700101,Electrónica,Monitor 24 pulgadas,50000000.0,...,200000000.0,45,cliente100116@yahoo.es,Alto,Oro,Rápido y sin problemas,1112.0,2026-05-27,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589411,P214545,C147031,2026-03-19,Tienda,Tarjeta,Cartagena,1300101,Hogar,Set de cuchillos,155400.0,...,155400.0,60,NaN,Bajo,Platino,Muy buen precio,11.7,2027-08-26,0,False
589416,P231923,C27475,2025-01-20,Marketplace,Tarjeta,Ibagué,7300101,Belleza,Secador de pelo,213800.0,...,1069000.0,200,NaN,Bajo,Bronce,Llegó incompleto el pedido,12.3,2027-08-11,1,False
589420,P307845,C136455,2026-05-14,Tienda,Paypal,Cartagena,1300105,Juguetería,Carro a control remoto,303700.0,...,303700.0,45,NaN,Alto,Plata,Llegó incompleto el pedido,14.4,2026-04-03,0,False
589422,P238956,C74804,2025-12-04,Web,Paypal,Villavicencio,5000103,Moda,Camisa de lino,470800.0,...,941600.0,20,NaN,Medio,Oro,Pésima experiencia con el empaque,10.2,2026-06-29,0,False
589426,P543968,C141410,2026-02-18,App,Transferencia,Villavicencio,5000101,Electrónica,Monitor 24 pulgadas,111400.0,...,111400.0,56,NaN,Alto,Bronce,Rápido y sin problemas,12.0,2026-06-18,0,False

In [13]:
filas_antes = df.shape[0]

In [14]:
df["_nulos_count"] = df.isnull().sum(axis=1)

df = df.sort_values(by=["fecha_pedido", "_nulos_count"], ascending=[True, False])

df = df.drop_duplicates(subset=["correo_cliente"], keep="last")

df = df.drop(columns=["_nulos_count"])

In [15]:
df.to_csv("S06_PD_Gonzalez_DatasetDepurado.csv", index=False)

## Etapa 2: Tratamiento de valores atípicos y ruido

In [16]:
import pandas as pd

df = pd.read_csv("S06_PD_Gonzalez_DatasetDepurado.csv")

In [17]:
Q1 = df["monto_compra"].quantile(0.25)
Q3 = df["monto_compra"].quantile(0.75)
IQR = Q3 - Q1

In [18]:
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

print("limite inferior:", limite_inferior)
print("limite superior:", limite_superior)

limite inferior: -728800.0
limite superior: 1808800.0

In [19]:
limite_inferior = 1

In [20]:
outliers_iqr = df[(df["monto_compra"] < limite_inferior) | (df["monto_compra"] > limite_superior)]

In [21]:
media = df["monto_compra"].mean()
desviacion = df["monto_compra"].std()

In [22]:
df["z_monto_compra"] = (df["monto_compra"] - media) / desviacion

In [23]:
df["es_venta_corporativa"] = df["monto_compra"] > limite_superior

In [24]:
df.loc[~df["es_venta_corporativa"], "monto_compra"] = df.loc[~df["es_venta_corporativa"], "monto_compra"].clip(upper=limite_superior, lower=limite_inferior)

In [25]:
ventas_diarias = df.groupby("fecha_pedido")["monto_compra"].sum().reset_index()

In [26]:
ventas_diarias["suavizado"] = ventas_diarias["monto_compra"].rolling(window=7).mean()

In [27]:
df.to_csv("S07_PD_Gonzalez_DatasetSinOutliers.csv", index=False)

## Etapa 3: Escalado de variables numéricas

In [28]:
import pandas as pd
df = pd.read_csv("S07_PD_Gonzalez_DatasetSinOutliers.csv")

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
df_entrenamiento, df_prueba = train_test_split(df, test_size=0.2, random_state=42)

In [31]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [32]:
escalador_edad = StandardScaler()
escalador_unidades = MinMaxScaler()
escalador_monto = RobustScaler()

escalador_edad.fit(df_entrenamiento[["edad_cliente"]])
escalador_unidades.fit(df_entrenamiento[["unidades_vendidas"]])
escalador_monto.fit(df_entrenamiento[["monto_compra"]])

RobustScaler()

In [33]:
df_entrenamiento["edad_cliente_escalada"] = escalador_edad.transform(df_entrenamiento[["edad_cliente"]])
df_entrenamiento["unidades_vendidas_escalada"] = escalador_unidades.transform(df_entrenamiento[["unidades_vendidas"]])
df_entrenamiento["monto_compra_escalado"] = escalador_monto.transform(df_entrenamiento[["monto_compra"]])

df_prueba["edad_cliente_escalada"] = escalador_edad.transform(df_prueba[["edad_cliente"]])
df_prueba["unidades_vendidas_escalada"] = escalador_unidades.transform(df_prueba[["unidades_vendidas"]])
df_prueba["monto_compra_escalado"] = escalador_monto.transform(df_prueba[["monto_compra"]])

In [34]:
import matplotlib.pyplot as plt

In [35]:
df_final = pd.concat([df_entrenamiento, df_prueba])

In [36]:
df_final.to_csv("S08_PD_Gonzalez_DatasetEscalado.csv", index=False)

## Etapa 4: Codificación de variables categóricas

In [37]:
import pandas as pd
df = pd.read_csv("S08_PD_Gonzalez_DatasetEscalado.csv")

In [38]:
from sklearn.preprocessing import OneHotEncoder

In [39]:
columnas_nominales = ["canal_compra", "metodo_pago", "ciudad_tienda", "categoria_producto", "comentario_cliente"]

df_codificado = pd.get_dummies(df, columns=columnas_nominales, prefix=["canal", "pago", "ciudad", "cat", "comentario"], dtype=int)

In [40]:
from sklearn.preprocessing import OrdinalEncoder

orden_lealtad = ["Bronce", "Plata", "Oro", "Platino"]

codificador_lealtad = OrdinalEncoder(categories=[orden_lealtad])
df_codificado["nivel_lealtad_cod"] = codificador_lealtad.fit_transform(df_codificado[["nivel_lealtad"]])

df_codificado[["nivel_lealtad", "nivel_lealtad_cod"]].drop_duplicates()

  nivel_lealtad  nivel_lealtad_cod
0       Platino                3.0
1        Bronce                0.0
5         Plata                1.0
6           Oro                2.0

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
df_entrenamiento, df_prueba = train_test_split(df, test_size=0.2, random_state=42)

In [43]:
from category_encoders import TargetEncoder

In [44]:
codificador_ciudad = TargetEncoder(cols=["ciudad_tienda"], smoothing=10)

codificador_ciudad.fit(df_entrenamiento["ciudad_tienda"], df_entrenamiento["monto_compra"])

TargetEncoder(cols=['ciudad_tienda'])

In [45]:
df_entrenamiento["ciudad_tienda_cod"] = codificador_ciudad.transform(df_entrenamiento["ciudad_tienda"])
df_prueba["ciudad_tienda_cod"] = codificador_ciudad.transform(df_prueba["ciudad_tienda"])

In [46]:
conteo_postal = df_entrenamiento["codigo_postal"].value_counts()

postales_frecuentes = conteo_postal[conteo_postal >= 15].index

df_entrenamiento["codigo_postal_agrupado"] = df_entrenamiento["codigo_postal"].where(
    df_entrenamiento["codigo_postal"].isin(postales_frecuentes), "Otras"
)

df_prueba["codigo_postal_agrupado"] = df_prueba["codigo_postal"].where(
    df_prueba["codigo_postal"].isin(postales_frecuentes), "Otras"
)

In [47]:
df_entrenamiento.to_csv("S09_PD_Gonzalez_DatasetCodificado.csv", index=False)

## Etapa 5: Transformaciones de fecha, texto y discretización

In [48]:
import pandas as pd
df = pd.read_csv("S09_PD_Gonzalez_DatasetCodificado.csv")

In [49]:
df["fecha_pedido"] = pd.to_datetime(df["fecha_pedido"])

In [50]:
df["mes_pedido"] = df["fecha_pedido"].dt.month
df["trimestre_pedido"] = df["fecha_pedido"].dt.quarter
df["dia_semana_pedido"] = df["fecha_pedido"].dt.dayofweek
df["es_fin_semana_pedido"] = (df["fecha_pedido"].dt.dayofweek >= 5).astype(int)

df[["fecha_pedido", "mes_pedido", "trimestre_pedido", "dia_semana_pedido", "es_fin_semana_pedido"]].head()

,fecha_pedido,mes_pedido,trimestre_pedido,dia_semana_pedido,es_fin_semana_pedido
0,2025-05-30,5.0,2.0,4.0,0
1,2025-05-11,5.0,2.0,6.0,1
2,2025-08-09,8.0,3.0,5.0,1
3,2025-09-03,9.0,3.0,2.0,0
4,2025-06-04,6.0,2.0,2.0,0

In [51]:
df["comentario_cliente"] = df["comentario_cliente"].fillna("")

In [52]:
df["longitud_comentario"] = df["comentario_cliente"].str.len()
df["num_palabras_comentario"] = df["comentario_cliente"].str.split().str.len()
df["tiene_comentario"] = (df["longitud_comentario"] > 0).astype(int)
df["menciona_demora"] = df["comentario_cliente"].str.contains("demor", case=False, na=False).astype(int)

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
df_entrenamiento, df_prueba = train_test_split(df, test_size=0.2, random_state=42)

In [55]:
df["grupo_edad"] = pd.cut(
    df["edad_cliente"],
    bins=[17, 25, 35, 45, 60, 100],
    labels=["18 a 25", "26 a 35", "36 a 45", "46 a 60", "61 y más"]
)

In [56]:
from sklearn.model_selection import train_test_split

df_entrenamiento, df_prueba = train_test_split(df, test_size=0.2, random_state=42)

In [57]:
df["monto_compra"].skew()

np.float64(99.57723417016936)

In [58]:
import numpy as np

df["monto_compra_log"] = np.log1p(df["monto_compra"])

df_entrenamiento["monto_compra_log"] = np.log1p(df_entrenamiento["monto_compra"])
df_prueba["monto_compra_log"] = np.log1p(df_prueba["monto_compra"])

In [59]:
df["monto_compra_log"].skew()

np.float64(-1.7562647250790617)

In [60]:
from sklearn.preprocessing import PowerTransformer

In [61]:
from sklearn.preprocessing import PowerTransformer

transformador_boxcox = PowerTransformer(method="box-cox")

transformador_boxcox.fit(df_entrenamiento[["monto_compra"]])

PowerTransformer(method='box-cox')

In [62]:
df_entrenamiento["monto_compra_boxcox"] = transformador_boxcox.transform(df_entrenamiento[["monto_compra"]])
df_prueba["monto_compra_boxcox"] = transformador_boxcox.transform(df_prueba[["monto_compra"]])

In [63]:
df_final = pd.concat([df_entrenamiento, df_prueba])

In [64]:
df_final = pd.concat([df_entrenamiento, df_prueba])

df_final.to_csv("S10_PD_Gonzalez_DatasetTransformado.csv", index=False)

In [65]:
pd.read_csv("S10_PD_Gonzalez_DatasetTransformado.csv")

,id_pedido,id_cliente,fecha_pedido,canal_compra,metodo_pago,ciudad_tienda,codigo_postal,categoria_producto,producto,precio_unitario,...,trimestre_pedido,dia_semana_pedido,es_fin_semana_pedido,longitud_comentario,num_palabras_comentario,tiene_comentario,menciona_demora,grupo_edad,monto_compra_log,monto_compra_boxcox
0,P144523,C151841,2026-01-03,App,Efectivo,Santa Marta,4700101,Moda,Camisa de lino,213200.0,...,1.0,5.0,1,29,5,1,0,26 a 35,13.656282,0.252655
1,P100654,C113355,2026-04-18,App,Transferencia,Barranquilla,800121,Juguetería,Set de bloques,594900.0,...,2.0,5.0,1,0,0,0,0,46 a 60,13.296150,0.139247
2,P311561,C49881,2025-06-01,Web,Tarjeta,Cali,7600103,Electrónica,Monitor 24 pulgadas,614000.0,...,2.0,6.0,1,22,5,1,0,26 a 35,0.693147,-2.569588
3,P706819,C101320,2025-02-06,Web,Transferencia,Cali,7600101,Hogar,Lámpara de escritorio,114500.0,...,1.0,3.0,0,32,5,1,1,61 y más,12.341482,-0.148126
4,P126175,C109379,2025-03-19,Web,Transferencia,Cartagena,1300103,Electrónica,Teclado mecánico,610400.0,...,1.0,2.0,0,24,4,1,0,26 a 35,14.708165,0.600468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381711,P471797,C48649,2025-12-24,Marketplace,Efectivo,Medellín,500106,Belleza,Perfume cítrico,78500.0,...,4.0,2.0,0,15,3,1,0,NaN,11.270867,-0.448712
381712,P274339,C145853,2025-01-24,Marketplace,Tarjeta,Barranquilla,800101,Belleza,Crema hidratante,86300.0,...,1.0,4.0,0,24,4,1,0,NaN,11.365596,-0.423000
381713,P326263,C92526,2027-09-16,Marketplace,Transferencia,Villavicencio,5000101,Moda,Zapatos deportivos,737700.0,...,3.0,3.0,0,26,4,1,0,26 a 35,14.204440,0.430764
381714,P557609,C92279,2025-01-03,Marketplace,Transferencia,Bogotá,1100102,Hogar,Olla a presión,273800.0,...,1.0,4.0,0,26,4,1,0,26 a 35,12.520157,-0.095768
381715,P335072,C134392,NaN,Tienda,Paypal,Cartagena,1300105,Electrónica,Teclado mecánico,315800.0,...,NaN,NaN,0,24,4,1,0,26 a 35,12.662868,-0.053484

In [66]:
df_final.shape

(381716, 39)

In [67]:
df_final.columns

Index(['id_pedido', 'id_cliente', 'fecha_pedido', 'canal_compra',
       'metodo_pago', 'ciudad_tienda', 'codigo_postal', 'categoria_producto',
       'producto', 'precio_unitario', 'unidades_vendidas', 'monto_compra',
       'edad_cliente', 'correo_cliente', 'nivel_satisfaccion', 'nivel_lealtad',
       'comentario_cliente', 'peso_pedido_kg', 'fecha_actualizacion_stock',
       'fuga_cliente', 'nivel_satisfaccion_imputado', 'z_monto_compra',
       'es_venta_corporativa', 'edad_cliente_escalada',
       'unidades_vendidas_escalada', 'monto_compra_escalado',
       'ciudad_tienda_cod', 'codigo_postal_agrupado', 'mes_pedido',
       'trimestre_pedido', 'dia_semana_pedido', 'es_fin_semana_pedido',
       'longitud_comentario', 'num_palabras_comentario', 'tiene_comentario',
       'menciona_demora', 'grupo_edad', 'monto_compra_log',
       'monto_compra_boxcox'],
      dtype='object')

## Diccionario de datos

| Columna del dataset | De qué semana viene | Qué significa |
| :--- | :--- | :--- |
| **z_monto_compra** | Semana 7 | *Z-score* del monto de compra para medir cuántas desviaciones estándar se aleja de la media. |
| **es_venta_corporativa** | Semana 7 | Indicador booleano que identifica si la compra superó el límite superior de outliers por IQR. |
| **edad_cliente_escalada** | Semana 8 | Edad del cliente estandarizada con `StandardScaler` . |
| **unidades_vendidas_escalada** | Semana 8 | Unidades vendidas escaladas mediante `MinMaxScaler`. |
| **monto_compra_escalado** | Semana 8 | Monto de compra transformado con `RobustScaler`para mitigar el efecto de atípicos. |
| **canal_\***, **pago_\***, **ciudad_\***, **cat_\*** | Semana 9 | Variables binarias (0/1) creadas por One-Hot Encoding (`get_dummies`) para representar las variables categóricas nominales. |
| **nivel_lealtad_cod** | Semana 9 | Codificación numérica ordinal del nivel de lealtad (Bronce=0, Plata=1, Oro=2, Platino=3). |
| **ciudad_tienda_cod** | Semana 9 | Codificación por objetivo (*Target Encoding*) de la ciudad con base en la media del `monto_compra`. |
| **codigo_postal_agrupado** | Semana 9 | Código postal que conserva las zonas de alta frecuencia y agrupa las demás bajo "Otras". |
| **mes_pedido** | Semana 10 | Mes del año (1 a 12) extraído de la fecha del pedido. |
| **trimestre_pedido** | Semana 10 | Trimestre del año (1 a 4) extraído de la fecha del pedido. |
| **dia_semana_pedido** | Semana 10 | Día de la semana (0 = Lunes, 6 = Domingo) extraído de la fecha. |
| **es_fin_semana_pedido** | Semana 10 | Variable binaria (1 si el pedido fue en sábado o domingo, 0 si fue día hábil). |
| **longitud_comentario** | Semana 10 | Cantidad total de caracteres presentes en el comentario del cliente. |
| **num_palabras_comentario** | Semana 10 | Número de palabras contadas en el comentario del cliente. |
| **tiene_comentario** | Semana 10 | Indicador binario (1 si el cliente escribió comentario, 0 si estaba vacío). |
| **menciona_demora** | Semana 10 | Indicador binario (1 si el comentario contiene la palabra/raíz "demor", 0 si no). |
| **grupo_edad** | Semana 10 | Categorización por rangos de edad ("18 a 25", "26 a 35", etc.) obtenida con `pd.cut`. |
| **monto_compra_log** | Semana 10 | Transformación logarítmica (`np.log1p`) aplicada al monto de compra para reducir la asimetría. |
| **monto_compra_boxcox** | Semana 10 | Transformación de potencia Box-Cox aplicada al monto de compra para normalizar la distribución. |

In [68]:
df_final.to_csv("S11_PD_Gonzalez_DatasetTransformado.csv", index=False)

df_final.shape

(381716, 39)

In [69]:
df_final.columns

Index(['id_pedido', 'id_cliente', 'fecha_pedido', 'canal_compra',
       'metodo_pago', 'ciudad_tienda', 'codigo_postal', 'categoria_producto',
       'producto', 'precio_unitario', 'unidades_vendidas', 'monto_compra',
       'edad_cliente', 'correo_cliente', 'nivel_satisfaccion', 'nivel_lealtad',
       'comentario_cliente', 'peso_pedido_kg', 'fecha_actualizacion_stock',
       'fuga_cliente', 'nivel_satisfaccion_imputado', 'z_monto_compra',
       'es_venta_corporativa', 'edad_cliente_escalada',
       'unidades_vendidas_escalada', 'monto_compra_escalado',
       'ciudad_tienda_cod', 'codigo_postal_agrupado', 'mes_pedido',
       'trimestre_pedido', 'dia_semana_pedido', 'es_fin_semana_pedido',
       'longitud_comentario', 'num_palabras_comentario', 'tiene_comentario',
       'menciona_demora', 'grupo_edad', 'monto_compra_log',
       'monto_compra_boxcox'],
      dtype='object')